# Generated by Django 5.2.6 on 2025-10-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_number', models.CharField(max_length=255, verbose_name='Filing Number')),
                ('filing_date', models.DateField(verbose_name='Filing Date')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Registration Number')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('cnr_number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='CNR Number')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='First Hearing Date')),
                ('next_hearing_date', models.DateField(blank=True, null=True, verbose_name='Next Hearing Date')),
                ('stage_of_case', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage of Case')),
                ('court_number_and_judge', models.CharField(blank=True, max_length=255, null=True, verbose_name='Court Number and Judge')),
                ('bench_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bench Type')),
                ('judicial_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Judicial Branch')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('not_before_me', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not Before Me')),
                ('petitioner', models.TextField(verbose_name='Petitioner and Advocate')),
                ('respondent', models.TextField(verbose_name='Respondent and Advocate')),
                ('category', models.CharField(blank=True, max_length=512, null=True, verbose_name='Category')),
                ('sub_category', models.CharField(blank=True, max_length=512, null=True, verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_list_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cause List Type')),
                ('judge', models.CharField(blank=True, max_length=255, null=True)),
                ('business_on_date', models.DateField(blank=True, null=True, verbose_name='Business On Date')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name='Hearing Date')),
                ('purpose_of_hearing', models.TextField(blank=True, null=True, verbose_name='Purpose of Hearing')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='courts.case')),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case Histories',
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='IADetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_number', models.CharField(max_length=255, verbose_name='IA Number')),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_filing', models.CharField(max_length=50, verbose_name='Date of Filing')),
                ('next_date', models.CharField(max_length=50, verbose_name='Next Date')),
                ('ia_status', models.CharField(max_length=100, verbose_name='IA Status')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_details', to='courts.case')),
            ],
            options={
                'verbose_name': 'IA Detail',
                'verbose_name_plural': 'IA Details',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Order Number')),
                ('order_on', models.CharField(max_length=255, verbose_name='Order On')),
                ('judge', models.CharField(max_length=255)),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('pdf_url', models.URLField(max_length=1024, verbose_name='PDF URL')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courts.case')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
