# Generated by Django 5.2.6 on 2025-10-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.AlterModelOptions(
            name='casehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iadetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='case',
            name='bench_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_number_and_judge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='district',
        ),
        migrations.RemoveField(
            model_name='case',
            name='filing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='filing_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='first_hearing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='judicial_branch',
        ),
        migrations.RemoveField(
            model_name='case',
            name='next_hearing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='not_before_me',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='stage_of_case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='state',
        ),
        migrations.RemoveField(
            model_name='case',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='business_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='courts.case'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='cause_list_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='purpose_of_hearing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iadetail',
            name='date_of_filing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iadetail',
            name='ia_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iadetail',
            name='ia_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iadetail',
            name='next_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_on',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='pdf_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_number', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('registration_number', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courts.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('stage_of_case', models.CharField(blank=True, max_length=255, null=True)),
                ('court_number_and_judge', models.CharField(blank=True, max_length=255, null=True)),
                ('bench_type', models.CharField(blank=True, max_length=100, null=True)),
                ('judicial_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('not_before_me', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='courts.case')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=512, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=512, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_details', to='courts.case')),
            ],
        ),
    ]
