# Generated by Django 5.2.6 on 2025-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_case_options_alter_casehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('bench', models.TextField()),
                ('cause_list_type', models.CharField(max_length=100)),
                ('view_text', models.CharField(default='View', max_length=50)),
                ('view_href', models.URLField(max_length=500)),
                ('list_date', models.DateField(help_text='The date of the cause list')),
            ],
            options={
                'verbose_name_plural': 'Cause List Entries',
                'ordering': ['-list_date', 'serial_number'],
            },
        ),
    ]
