# Generated by Django 5.2.6 on 2025-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_causelistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('HC_CASE_DETAILS', 'High Court - Case Details'), ('HC_CAUSE_LIST', 'High Court - Cause List'), ('DC_CASE_DETAILS', 'District Court - Case Details'), ('DC_CAUSE_LIST', 'District Court - Cause List')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_json_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-requested_at'],
            },
        ),
    ]
